### ISSUE TITLE
Duplicate Example in multiple Intents

### ISSUE THREAD

**Issue by thiagopromano** [wallali/watsn-conversation-tool#5]
Hi,

I was wondering if it is possible to locate if an Example appear in more than one Intent.

Great tool btw!

**Comment by sparkhead95** [comment]
Hi,

I'm afraid this is not possible with the current version. You can output all intents (with their examples) that have been updated within a given timeframe, by using:
`watsncv search -p -o --intents --after 2017-11-14 --before 2017-11-16 [filename.json]`.
This might help for now, in case you're worried your duplicate examples were added recently.
